name: Docker Image CI (Upload Tag) # workflow 이름 : Docker Image CI (Upload Tag)

on:  # workflow를 발생시키는 이벤트 
  push: # 'v*인 tag를 push할 때
    tags:
      - 'v*'

jobs: # workflow의 내용 

  build: # 빌드할 때 실행할 workflow 

    runs-on: ubuntu-latest  #  ubuntu-latest에서 실행 (runner)

    steps:   # 일련의 tasks
    - name: Checkout                        # task이름 : Checkout
      uses: actions/checkout@v3              # actions/checkout@v3에서 정의된 action 실행
    - name: Buildx                            # task이름 :Buildx
      uses: docker/setup-buildx-action@v1     # docker/setup-buildx-action@v1에서 정의된 action 실행

    -
      name: Docker meta               # task이름 :  Docker meta  
      id: meta                         # id (step의 식별자): meta
      uses: docker/metadata-action@v4 #docker/metadata-action@v4에 정의된 action 실행 
      with:                           # 사용될 docker이미지 전달
        images: amirpourmand/al-folio

    - name: Login                     # task이름 :Login 
      uses: docker/login-action@v1    #docker/login-action@v1 에서 정의된 action 실행
      with:                # secrets.DOCKER_USERNAME과 secrets.DOCKER_PASSWORD을 호출된 workflow에 전달
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push         # task이름 : Build and push 
      uses: docker/build-push-action@v3   # docker/build-push-action@v3에서 정의된 action 실행
      with:                               # 호출된 workflow에 input으로 전달할 것
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

